### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by amzar96** [centrifugal/pycent#26]
Hi,

```python
from cent import Client, CentException

url = "https://localhost:8999"
api_key = "xxxxx"
client = Client(url, api_key=api_key, timeout=1)

client.channels()
```

when I ran the above code, got the below error

`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by FZambia** [comment]
Hello @amzar96 , please provide steps to reproduce including versions of Centrifugo server and client you have.

**Comment by FZambia** [comment]
Could you try `url = "https://localhost:8999/api"` instead of `url = "https://localhost:8999"`?
