### ISSUE TITLE
[Question] Broadcast method input parameters

### ISSUE THREAD

**Issue by duy-nguyen-ts** [centrifugal/pycent#28]
Hi sir, I want to using cent in backend to broadcast a event/message to Centrifugo. And I want to using feature `async consumers`with it so I need to use `idempotency_key` to prevent duplicated event when retry. But I read the code that the broadcast method does not have `idempotency_key` parameter, right ?
![image](https://github.com/centrifugal/pycent/assets/140502993/48ee1845-872f-4045-a0e0-2c75ce176931)

**Comment by FZambia** [comment]
Hello @duy-nguyen-ts 

`idempotency_key` is not supported by this library, it was not updated for quite a long time. We are close to release a new version of py-`cent` -  the latest work is in https://github.com/centrifugal/pycent/tree/send_any_request branch, I can't say when exactly it will be released, still need some work. But I believe it will happen soon. It will support latest API fields.

So `idempotency_key` is generally supported by broadcast command - just not implemented in this lib in its latest version.

**Comment by duy-nguyen-ts** [comment]
Thanks @FZambia
